name: Test Deploy

on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Setup Project
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install Dependencies
        run: npm run
      - name: Deploy SST Proj
        run: npm run deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET }}
